name: clang-format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Prepare build environment
      run: |
        sudo apt update
        sudo apt-get install ninja-build gcovr

    - name: Configure CMake
      run: cmake --preset=release
    - name: Check C++ Formatting
      run: cmake --build build --target check-clang-format
    - name: Check CMake Formatting
      run: cmake --build build --target check-cmake-format
