name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [{cpp: g++-10, c: gcc-10}]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Prepare build environment
      run: |
        sudo apt update
        sudo apt-get install ninja-build

    - name: Configure CMake
      run: cmake --preset=relwithdeb -DPASTA_BIT_VECTOR_BUILD_TESTS=On
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build_with_debug_info/

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build_with_debug_info/
      