name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake --preset=relwithdeb -DPASTA_BIT_VECTOR_BUILD_TESTS=On

    - name: Build
      run: cmake --build ${{github.workspace}}/build_with_debug_info/

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build_with_debug_info/
      