name: pasta::bit_vector CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [{cpp: g++-10, c: gcc-10}]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PRIVATE_SUBMODULE_ACCESS }}
        submodules: true

    - name: Prepare build environment
      run: |
        sudo apt update
        sudo apt-get install ninja-build gcovr

    - name: Configure CMake
      run: cmake --preset=relwithdeb -DPASTA_BIT_VECTOR_BUILD_TESTS=On -DPASTA_BIT_VECTOR_COVERAGE_REPORTING=On
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build_with_debug_info/

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build_with_debug_info/

    - name: Run gcovr
      run: |
        mkdir ${{github.workspace}}/coverage
        gcovr -r . -e extlib/ -e tests/ --xml-pretty | tee ${{github.workspace}}/coverage/coverage.xml

    - name: Upload Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: ${{github.workspace}}/coverage/coverage.xml
